export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const SET_POST_DETAILS = 'SET_POST_DETAILS';
export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';
export const SET_COMMENTS_FOR_POST = 'SET_COMMENTS_FOR_POST';
